package com.kerwin.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.kerwin.bean.Channels;

import com.kerwin.bean.ChannelsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig channelsDaoConfig;

    private final ChannelsDao channelsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        channelsDaoConfig = daoConfigMap.get(ChannelsDao.class).clone();
        channelsDaoConfig.initIdentityScope(type);

        channelsDao = new ChannelsDao(channelsDaoConfig, this);

        registerDao(Channels.class, channelsDao);
    }
    
    public void clear() {
        channelsDaoConfig.getIdentityScope().clear();
    }

    public ChannelsDao getChannelsDao() {
        return channelsDao;
    }

}
